### ISSUE TITLE
Investigate turpy process terminating

### ISSUE THREAD

**Issue by rensoftworks** [ultrasaber/turpy#3]
- May need to implement better promise handling
- ~~May need to monitor and log websocket events~~
- Implement a method to address turpy terminating in this way.
- Implement better monitoring to address turpy terminating immediately

Related stack trace from log:
```(node:17770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: Missing Permissions
(node:17770) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Permissions
(node:17770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): DiscordAPIError: Missing Permissions
(node:17770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): DiscordAPIError: Missing Permissions
(node:17770) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): DiscordAPIError: Missing Permissions
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest._req.on (/home/turpy/turpy/node_modules/ws/lib/WebSocket.js:650:26)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

**Comment by rensoftworks** [comment]
Implemented logging module to better determine the cause of this issue. Will return to this when we see this issue again.
